spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogapplication
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    hibernate:
      ddl-auto: update
  jackson:
    mapper:
      accept-case-insensitive-properties: true
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type: info

jwt:
  secret_key: vrajshahvrajshah
  expire_in: 50

cookie:
  secure: true
  http_only: false
